StationaryReuse/StationaryReuse/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from myapp import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('registration/', views.UserRegistrationView, name="user_registration"),
    path('login/', views.UserLoginView, name="user_login"),
    path('logout/', views.UserLogoutView, name="user_logout"),
    path('profile/', include('myapp.urls')),
    path('', views.HomePageView, name="home"),  # for the unsigned user.
    path('user/<str:username>/', views.HomePageView, name="loginhome"),  # for the signed in user.
    path('<str:username>/postad/', views.PostAdView, name="postad"),
    path('ad-description/<int:pk>/', views.AdDescriptionView, name="ad_description"),
    path('user/<str:username>/booksads/', views.ViewBookAds, name="booksads"),
    path('user/<str:username>/stationaryads/', views.ViewStationaryAds, name="stationaryads"),
    path('user/<str:username>/uniformads/', views.ViewUniformAds, name="uniformads"),
    path('user/<str:username>/otherads/', views.ViewOtherAds, name="otherads"),
    path('favourites/<str:username>/', views.ViewFavouriteAds, name="favourites"),
    path('favourites/<str:username>/<int:pk>/<str:purpose>/', views.ViewFavouriteAds, name="favourites"), # URL to remove an add from the favourite ad option.
    path('postedads/<str:username>/', views.ViewPostedAds, name="postedads"),
    path('postedads/<str:username>/<int:pk>/', views.ViewPostedAds, name="postedads"),  # URL for deleting a posted ad.
    path('chat/', include('chat.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

StationaryReuse/chat/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.message_inbox, name = "message_inbox"),
    path('<int:receiver_id>/', views.text_person, name="text_person"),
]

StationaryReuse/myapp/urls.py
from django.conf.urls import include
from django.urls import path
from myapp import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'user'

urlpatterns = [
    path('<str:username>/', views.UserProfileView, name="profile"),
    path('<str:username>/editprofile/', views.UserEditProfileView, name="edit_profile")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

StationaryReuse/myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.

class UserInfoModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="child_user")
    profile_pic = models.ImageField(upload_to="photos/userprofilepics", blank=True)
    description = models.CharField(max_length=250, blank=True)
    phone_number = models.PositiveSmallIntegerField(null=True)
    college = models.CharField(max_length=40, blank=True)
    branch = models.CharField(max_length=40, blank=True)
    address = models.CharField(max_length=50, blank=True)
    gender = models.CharField(max_length=10, default="", blank=True, null=True)
    
    def __str__(self):
        return self.user.username


class AdsInfoModel(models.Model):
    user = models.ForeignKey(UserInfoModel, on_delete=models.CASCADE, related_name="posted_ads")
    purpose = models.CharField(max_length=10)
    category = models.CharField(max_length=10)
    title = models.CharField(max_length=50)
    price = models.FloatField(blank=True)
    description = models.TextField()
    posted_date = models.DateField()
    
    def __str__(self):
        return self.title


class AdsPhotosModel(models.Model):
    pic_parent = models.ForeignKey(AdsInfoModel, on_delete=models.CASCADE, related_name="photos")
    photo = models.ImageField(upload_to="photos/adpics")


class FavouriteAdsModel(models.Model):
    user = models.ForeignKey(UserInfoModel, on_delete=models.CASCADE, related_name="favourite_ads")
    ad = models.OneToOneField(AdsInfoModel, on_delete=models.CASCADE)

StationaryReuse/myapp/forms.py
from django import forms
from django.contrib.auth.models import User


class UserRegistrationModelForm(forms.ModelForm):
    ConfirmPassword = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ['username', 'email', 'password']

    def clean(self):
        user_data = super().clean()
        if user_data['password'] != user_data['ConfirmPassword']:
            raise forms.ValidationError("Passwords did not match!")
        return user_data


class UserLoginModelForm(forms.ModelForm):
    class Meta():
        model = User
        fields = ['username','password']


class UserInfoModelForm(forms.ModelForm):
    pass

StationaryReuse/myapp/views.py
from django.shortcuts import render
from myapp.forms import UserLoginModelForm, UserRegistrationModelForm
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView
from django.contrib.auth.models import User
from myapp.models import UserInfoModel, AdsInfoModel, AdsPhotosModel, FavouriteAdsModel
from django.urls import reverse
from django.utils import timezone
import random
from datetime import datetime
from dateutil.relativedelta import relativedelta

# Create your views here.

@login_required
def UserLogoutView(request):
    logout(request)
    return HttpResponseRedirect(reverse('user_login'))


def UserLoginView(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('loginhome', kwargs={'username': username}))
        else:
            return HttpResponse("YOU MADE A BLUNDER")
    else:
        return render(request, 'myapp/UserLogin.html')


def UserRegistrationView(request):
    if request.method=="POST":
        username = request.POST.get("username")
        email = request.POST.get("email")
        password = request.POST.get("password")
        confirm_password = request.POST.get("confirm_password")
        if password == confirm_password:
            user = User.objects.create(username=username, email=email, password=password)
            user.set_password(user.password)
            user.save()
            user_info = UserInfoModel.objects.create(user=user)
            user_info.save()
            
            login(request, user)

            return HttpResponseRedirect(reverse('loginhome', kwargs={'username': username}))
        else:
            return HttpResponse("INVALID CREDENTIALS!")
    else:
        return render(request, 'myapp/UserRegistration.html')


@login_required
def UserProfileView(request, username):
    profile_user = User.objects.get(username=username)  #The user whose profile is to be viewed can be the current user or any other user.
    info = UserInfoModel.objects.get(user=profile_user)
    var_dict = {"profile_user": profile_user, "info": info}
    return render(request, "myapp/profile.html", context=var_dict)


@login_required
def UserEditProfileView(request, username):
    user = User.objects.get(username=username)
    info = UserInfoModel.objects.get(user=user)
    if request.method == "POST":
        name = str(request.POST.get("name"))
        #checking whether the user has entered the full name of just the first name and inserting the data accordingly in the table.
        if " " in name:
            user.first_name, user.last_name = name.split(" ")
        else:
            user.first_name = name
            user.last_name = ""
        user.email = request.POST.get("email")
        info.gender = request.POST.get("gender")
        info.college = request.POST.get("college")
        info.branch = request.POST.get("course")
        info.description = request.POST.get("description")
        info.phone_number = request.POST.get("phone_number")
        info.address = request.POST.get("address")
        if "profile_pic" in request.FILES:
            info.profile_pic = request.FILES.get("profile_pic")
        user.save()
        info.save()
        return HttpResponseRedirect(reverse("user:profile", kwargs={"username":username}))

    else:
        var_dict = {"user":user, "info":info}
        return render(request, "myapp/edit_profile.html", context=var_dict)


def HomePageView(request, username=None):
    ads = AdsInfoModel.objects.all().order_by("posted_date")[:14]
    books = AdsInfoModel.objects.filter(category="book")[:6]
    stationary = AdsInfoModel.objects.filter(category="stationary")[:6]
    costumes = AdsInfoModel.objects.filter(category="costume")[:6]
    others = AdsInfoModel.objects.filter(category="other")[:6]

    dateobj = datetime.now()
    n = 30
    past_date = dateobj - relativedelta(days = n)
    AdsInfoModel.objects.filter(posted_date__lt=past_date).delete()

    if (username != None):
        cur = User.objects.get(username=username)   # Getting the user from user model
        cur_user = UserInfoModel.objects.get(user=cur)  # Getting the user from userinfomodel
        temp_favourites = FavouriteAdsModel.objects.filter(user=cur_user)
        favourites = []
        for favourite in temp_favourites:
            favourites.append(favourite.ad.pk)
        return render(request, "myapp/home.html", context={"ads": ads, "books": books, "stationary": stationary, "costumes": costumes, "others": others, "favourites": favourites})
    else:
        return render(request, "myapp/home.html", context={"ads": ads, "books": books, "stationary": stationary, "costumes": costumes, "others": others})


@login_required
def PostAdView(request, username):
    user = User.objects.get(username=username)
    info = UserInfoModel.objects.get(user=user)
    if request.method == "POST":
        category = request.POST.get("category")
        title = request.POST.get("title")
        description = request.POST.get("description")
        purpose = request.POST.get("purpose")
        price = request.POST.get("price")
        posted_date = datetime.now()
        # Price in case of donation is a null string so filtering that out.
        if price=="":
            price = 0
        ad = AdsInfoModel.objects.create(title=title, category=category, description=description, purpose=purpose, price=price, user=info, posted_date=posted_date)
        ad.save()
        for pic in request.FILES:
            pic_instance = AdsPhotosModel.objects.create(pic_parent=ad, photo=request.FILES['ad_pic'])
            pic_instance.save()
        return HttpResponseRedirect(reverse("ad_description", kwargs={"pk":ad.pk}))

    else:
        return render(request, "myapp/postad.html", context={"user": user, "info": info})


@login_required
def AdDescriptionView(request, pk):
    ad = AdsInfoModel.objects.get(id=pk)
    var_dict = {'ad': ad}
    return render(request, "myapp/ad_description.html", context=var_dict)


@login_required
def ViewBookAds(request, username):
    books = AdsInfoModel.objects.filter(category="book")
    cur = User.objects.get(username=username)   # Getting the user from user model
    cur_user = UserInfoModel.objects.get(user=cur)  # Getting the user from userinfomodel
    temp_favourites = FavouriteAdsModel.objects.filter(user=cur_user)
    favourites = []
    for favourite in temp_favourites:
        favourites.append(favourite.ad.pk)
    return render(request, "myapp/booksads.html", context={"books": books, "favourites": favourites})


@login_required
def ViewStationaryAds(request, username):
    stationary = AdsInfoModel.objects.filter(category="stationary")
    cur = User.objects.get(username=username)   # Getting the user from user model
    cur_user = UserInfoModel.objects.get(user=cur)  # Getting the user from userinfomodel
    temp_favourites = FavouriteAdsModel.objects.filter(user=cur_user)
    favourites = []
    for favourite in temp_favourites:
        favourites.append(favourite.ad.pk)
    return render(request, "myapp/stationaryads.html", context={"stationary": stationary, "favourites": favourites})


@login_required
def ViewUniformAds(request, username):
    costumes = AdsInfoModel.objects.filter(category="costume")
    cur = User.objects.get(username=username)   # Getting the user from user model
    cur_user = UserInfoModel.objects.get(user=cur)  # Getting the user from userinfomodel
    temp_favourites = FavouriteAdsModel.objects.filter(user=cur_user)
    favourites = []
    for favourite in temp_favourites:
        favourites.append(favourite.ad.pk)
    return render(request, "myapp/costumesads.html", context={"costumes": costumes, "favourites": favourites})


@login_required
def ViewOtherAds(request, username):
    others = AdsInfoModel.objects.filter(category="other")
    cur = User.objects.get(username=username)   # Getting the user from user model
    cur_user = UserInfoModel.objects.get(user=cur)  # Getting the user from userinfomodel
    temp_favourites = FavouriteAdsModel.objects.filter(user=cur_user)
    favourites = []
    for favourite in temp_favourites:
        favourites.append(favourite.ad.pk)
    return render(request, "myapp/otherads.html", context={"others": others, "favourites": favourites})


@login_required
def ViewFavouriteAds(request, username, pk=None, purpose=None):
    cur = User.objects.get(username=username)   # Getting the user from user model
    cur_user = UserInfoModel.objects.get(user=cur)  # Getting the user from userinfomodel
    if (pk != None and purpose == "deletead"):
        ad = FavouriteAdsModel.objects.get(pk=pk)
        ad.delete()
    elif (pk != None and purpose == "seelater"):
        cur_ad = AdsInfoModel.objects.get(pk=pk)
        FavouriteAdsModel.objects.create(user=cur_user, ad=cur_ad)
    elif (pk != None and purpose == "deleteadnew"):
        ads = FavouriteAdsModel.objects.all()
        for ad in ads:
            if ad.ad.pk == pk:
                ad.delete()
                break
    favourites = FavouriteAdsModel.objects.filter(user=cur_user)
    return render(request, "myapp/favouriteads.html", context={"favourites": favourites})


@login_required
def ViewPostedAds(request, username, pk=None):
    cur = User.objects.get(username=username)   # Getting the user from user model
    cur_user = UserInfoModel.objects.get(user=cur)  # Getting the user from userinfomodel
    if (pk != None):
        ad = AdsInfoModel.objects.get(pk=pk)
        ad.delete()
    posted = AdsInfoModel.objects.filter(user=cur_user)

StationaryReuse/templates/myapp/UserLogin.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Login</title>
	<link rel="stylesheet" type="text/css" href="{% static "myapp/css/style.css" %}">
	<link href="https://fonts.googleapis.com/css?family=Poppins:600&display=swap" rel="stylesheet">
	<script src="https://kit.fontawesome.com/a81368914c.js"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<img class="wave" src="{% static "myapp/images/wave.png" %}">
	<div class="container">
		<div class="img">
			<img src="{% static "myapp/images/bg.svg" %}">
		</div>
		<div class="login-content">
			<form method="POST">
				{% csrf_token %}
				<img src="{% static "myapp/images/avatar.svg" %}">
				<h2 class="title">Welcome</h2>
           		<div class="input-div one">
           		   <div class="i">
           		   		<i class="fas fa-user"></i>
           		   </div>
           		   <div class="div">
           		   		<h5>Username</h5>
           		   		<input type="text" class="input" name="username">
           		   </div>
           		</div>
           		<div class="input-div pass">
           		   <div class="i"> 
           		    	<i class="fas fa-lock"></i>
           		   </div>
           		   <div class="div">
           		    	<h5>Password</h5>
           		    	<input type="password" class="input" name="password">
            	   </div>
            	</div>
            	<a href="#">Forgot Password?</a>
				<input type="submit" class="btn" value="Login">
				<a href="{% url "user_registration" %}" style="text-align: center;">Dont't Have an Account?/SignUp</a>
			</form>
        </div>
    </div>
    <script type="text/javascript" src="{% static "myapp/javascript/main.js" %}"></script>
</body>
</html>

StationaryReuse/templates/myapp/footer.html
<!DOCTYPE html>
<!-- code by webdevtrick ( https://webdevtrick.com ) -->
<html>

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="keywords" content="footer, address, phone, icons" />

  <title>Footer With Address And Phones</title>

  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
  <link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="css/footer.css">

</head>

<body>
  
  <footer class="footer-distributed">

    <div class="footer-left">

      <h3>iPassword<span>Generator</span></h3>

      <p class="footer-links">
        <a href="#">Privacy Policy</a>
        -
        <a href="#">Disclaimer</a>
        -
        <a href="#">About Us</a>

      </p>

      <p class="footer-company-name">Made By Dillip &copy; 2020</p>
    </div>

    <div class="footer-center">

      <div>
        <i class="fa fa-map-marker"></i>
        <p><span>FM Square, Balasore</span>Odisha, INDIA</p>
      </div>

      <div>
        <i class="fa fa-phone"></i>
        <p>+91 9692324552</p>
      </div>

      <div>
        <i class="fa fa-envelope"></i>
        <p><a href="mailto:support@company.com">contact@webdevtrick.com</a></p>
      </div>

    </div>

    <div class="footer-right">

      <p class="footer-company-about">
        <span>About the company</span>
        Web Dev Trick is a blog for web designers, graphic designers, web developers &amp; SEO Learner.
      </p>

      <div class="footer-icons">

        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-linkedin"></i></a>
        <a href="#"><i class="fa fa-github"></i></a>

      </div>

    </div>

  </footer>

</body>

</html>

StationaryReuse/templates/myapp/profile.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <title>Profile</title>
        <!-- Required meta tags always come first -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="x-ua-compatible" content="ie=edge">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static "myapp/css/profile.css" %}">
        <link rel="stylesheet" href="{% static "myapp/css/navigation.css" %}">
        <link rel="stylesheet" href="{% static "myapp/css/footer.css" %}">
        <link rel="stylesheet" href="{% static "myapp/css/home.css" %}">
        <script src="https://kit.fontawesome.com/b0c88f7d0f.js" crossorigin="anonymous"></script>
    </head>
    <body>
      <nav class="navigation">
        <div class="navigation__column">
          <a href="{% url "loginhome" username=user.username %}">
                <img src="{% static "myapp/images/logo.png" %}" />
            </a>
        </div>
        <div class="navigation__column">
            <ul class="navigations__links">
                {% if user.is_authenticated %}
                    <li class="navigation__list-item">
                        <a href="{% url "user:profile" username=user.username %}" class="navigation__link">
                            <i class="fa fa-user"></i>
                        </a>
                    </li>
                    <li class="navigation__list-item">
                      <a href="{% url "favourites" username=user.username %}" class="navigation__link">
                            <i class="fa fa-heart"></i>
                        </a>
                    </li>
                    <li class="navigation__list-item">
                        <a href="{% url "postad" username=user.username %}" class="navigation__link">
                            <i class="fa fa-plus"></i>
                        </a>
                    </li>
                    <li class="navigation__list-item" style="padding-top: 5px">
                      <a href="{% url "chat:message_inbox" %}" class="navigation__link">
                          <i class="fa-solid fa-envelope"></i>
                      </a>
                    </li>
                    <li class="navigation__list-item">
                        <a href="{% url "user_logout" %}" class="navigation__link">
                          <i class="fas fa-sign-out-alt"></i>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-12">
          <!-- <div style="text-align:center"> -->
          <h3>{{profile_user.username}}</h3>
          <hr color="black">
          <!-- </div> -->
        </div>
      </div>
        <div class="main-body">

              <div class="row gutters-sm">
                <div class="col-md-4 mb-3">
                  <div class="card">
                    <div class="card-body">
                      <div class="d-flex flex-column align-items-center text-center">
                        {% if info.profile_pic %}
                          <img src="{{info.profile_pic.url}}" alt="Admin" class="rounded-circle" width="150">
                        {% else %}
                          <img src="{% static "myapp/images/avatar.svg" %}" alt="Admin" class="rounded-circle" width="150">
                        {% endif %}
                        <div class="mt-3">
                          <p class="text-secondary mb-1">{{profile_user.email}}</p>
                          <!-- <p class="text-muted font-size-sm">College Name</p> -->
                        {% if user.username == profile_user.username %}
                          <a href="{% url "user:edit_profile" username=user.username %}" class="btn btn-outline-primary">Edit Profile</a>
                        {% else %}
                          <a href="{% url 'chat:text_person' receiver_id=profile_user.pk %}" class="btn btn-outline-primary">Message</a>
                        {% endif %}
                        </div>
                      </div>
                    </div>
                  </div>
                  <div style="padding-top:5%">
                    <div class="card">
                      <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                          <!-- <div class="card mt-3"> -->
                              <div class="mt-2">
                                  <h5>About</h5>
                                  <hr>
                                  <p>{{info.description}}</p>
                              </div>
                          <!-- </div> -->
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-md-8">
                  <div class="card mb-3">
                    <div class="card-body">
                      <div class="row">
                        <div class="col-sm-3">
                          <h6 class="mb-0">Full Name</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                          {{profile_user.get_full_name}}
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <h6 class="mb-0">Gender</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                          {{info.gender}}
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <h6 class="mb-0">Phone</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                          {{info.phone_number}}
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <h6 class="mb-0">Course</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {{info.branch|upper}}
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <h6 class="mb-0">College</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {{info.college|title}}
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <h6 class="mb-0">Address</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                          {{info.address}}
                        </div>
                      </div>
                    </div>
                  </div>
                    <div class="col-md-14">
                        <div class="card mb-3">
                            <div class="container-fluid bg-white my-1 py-2 border shadow">
                                <div class="row pt-3">
                                    <div class="col">
                                        <h4>Posted Ads</h4>
                                    </div>
                                    <div class="col col-sm-4 view-btn">
                                        <div>
                                          <a class="btn shadow" style="background-color: #20c997; color:white" href="{% url "postedads" username=user.username %}" class="navigation__link">View All</a>
                                        </div>
                                    </div>
                                </div>
                                <hr>
                        
                                <div class="row d-flex nowrap justify-content-center">
                                    {% for ads in info.posted_ads.all|slice:"0:3" %}
                                        <div class="card text-center sales">
                                            {% for pic in ads.photos.all|slice:"0:1" %}
                                                <img class="card-img-top p-2 img-fluid w-100" alt="Books" src="{{pic.photo.url}}">
                                            {% endfor %}
                                            <div class="card-body p-1" title="Shop Now!">
                                                <a href="{% url "ad_description" pk=ads.pk %}">
                                                    <h6 class="card-title">{{ads.title}}</h6>
                                                </a>
                                                <a href="{% url "ad_description" pk=ads.pk %}" class="card-link">{{ads.purpose}}</a>
                                                <a href="{% url "user:profile" username=ads.user.user.username %}">
                                                    <p class="card-subtitle text-muted">{{ads.user.user.get_full_name}}</p>
                                                </a>
                                                <a class="btn shadow" style="background-color: #20c997; color:white" href="{% url "postedads" username=user.username pk=ads.pk %}" class="navigation__link">Delete Ad</a>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                    {% if user.username == profile_user.username %}
                    <div class="col-md-14">
                        <div class="card mb-3">
                            <div class="container-fluid bg-white my-1 py-2 border shadow">
                                <div class="row pt-3">
                                    <div class="col">
                                        <h4>Favourite Ads</h4>
                                    </div>
                                    <div class="col col-sm-4 view-btn">
                                        <div>
                                            <a class="btn shadow" style="background-color: #20c997; color:white" href="{% url "favourites" username=user.username %}" class="navigation__link">View All</a>
                                        </div>
                                    </div>
                                </div>
                                <hr>
                        
                                <div class="row d-flex nowrap justify-content-center">
                                    {% for item in info.favourite_ads.all|slice:"0:3" %}
                                        <div class="card text-center sales">
                                            {% for pic in item.ad.photos.all|slice:"0:1" %}
                                                <img class="card-img-top p-2 img-fluid w-100" alt="Books" src="{{pic.photo.url}}">
                                            {% endfor %}
                                            <div class="card-body p-1" title="Shop Now!">
                                                <a href="{% url "ad_description" pk=item.ad.pk %}">
                                                    <h6 class="card-title">{{item.ad.title}}</h6>
                                                </a>
                                                <a href="{% url "ad_description" pk=item.ad.pk %}" class="card-link">{{item.ad.purpose}}</a>
                                                <a href="{% url "user:profile" username=item.ad.user.user.username %}">
                                                    <p class="card-subtitle text-muted">{{item.ad.user.user.get_full_name}}</p>
                                                </a>
                                                <a class="btn shadow" style="background-color: #20c997; color:white" href="{% url "favourites" username=user.username pk=item.pk purpose="deletead" %}" class="navigation__link">Remove Ad</a>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
      </div>
        
</body>

</html>